fix(planner/python):  Python DetermineFramework
zeabur/zbpack pull request #104
Opened 2023-06-27 04:21 UTC by ScmTble

2023-06-27 06:36 UTC, pan93412 requested changes

2023-06-27 06:36 UTC, pan93412 commented on internal/python/plan_test.go
> -	assert.False(t, HasDependency(ctx, "bar"))
Why removes this test?

2023-06-27 06:36 UTC, pan93412 commented on internal/python/plan_test.go
> -	assert.False(t, HasDependency(ctx, "bar"))
Don't modify the current test. You can copy a new function based on your new `HasDependencyWithFile` with `TestHashDependencyWithFile_` prefixed.

2023-06-27 06:43 UTC, ScmTble commented on internal/python/plan_test.go
> -	assert.False(t, HasDependency(ctx, "bar"))
check Dependency in Pipfile not in Pipfile.lock TestHasDependency_PipenvDep has check

2023-06-27 06:50 UTC, pan93412 commented on internal/python/plan_test.go
> -	assert.False(t, HasDependency(ctx, "bar"))
我觉得留着也没关系，或许有人依赖这个行为 🤔  如果要删的话，我印象中我还有 `poetry.lock` 的对应测试，这部份也可能需要你检查一下～

2023-06-28 02:17 UTC, pan93412 approved these changes

2023-06-30 04:59 UTC, merged