feat(identify/hugo): support hugo configuration directory mode & test case
zeabur/zbpack pull request #161
Opened 2023-10-19 13:50 UTC by MashiroWang

<img width="779" alt="image" src="https://github.com/zeabur/zbpack/assets/10394160/8e635025-3513-4247-ad61-3a474fdf8620">

Enhance the detection of the Hugo framework by searching in `config/_default`

2023-10-19 14:15 UTC, MashiroWang commented on internal/static/identify.go
> +	configFiles, err := afero.ReadDir(options.Source, "/config/_default")
of course, fixed.

2023-10-19 14:15 UTC, MashiroWang commented on public/categories/index.xml
> +<?xml version="1.0" encoding="utf-8" standalone="yes"?>
sorry my fault.

2023-10-19 14:28 UTC, pan93412 requested changes

2023-10-19 14:28 UTC, pan93412 commented on internal/static/identify.go
> +	return hasFile
```suggestion
	return utils.HasFile(fs, "index.html", "hugo.toml", "config/_default/hugo.toml")
```

I did not verify if this works.

2023-10-19 14:28 UTC, pan93412 commented on internal/static/identify.go
> +	}
```suggestion
	if utils.HasFile(hugoConfigSource, "config/_default/hugo.toml") {
		return types.PlanMeta{"framework": "hugo"}
	}
```

2023-10-19 14:39 UTC, MashiroWang commented on internal/static/identify.go
> +	return hasFile
perfect suggestion

2023-10-19 14:39 UTC, MashiroWang commented on internal/static/identify.go
> +	}
perfect suggestion

2023-10-20 01:40 UTC, MashiroWang commented
I think I can use glob pattern to match multiple Hugo config file extensions.

2023-10-20 05:53 UTC, MashiroWang commented
> I think I can use glob pattern to match multiple Hugo config file extensions.

Afero glob unsupported list pattern like `{hugo,config}.{toml,yaml}`.
This solution is not feasible.

2023-10-20 07:05 UTC, pan93412 approved these changes

2023-10-20 07:10 UTC, merged