ZEA-2031: implement handle raw html static build
zeabur/zbpack pull request #167
Opened 2023-10-26 11:54 UTC by hackerchai

2023-10-26 12:11 UTC, pan93412 requested changes

2023-10-27 11:36 UTC, pan93412 requested changes

2023-10-27 11:36 UTC, pan93412 commented on internal/static/identify.go
>  		return types.PlanMeta{"framework": "hugo"}
Hugo 不會有 public/index.html 嗎？我建議把 html-static 放到最下面。

2023-10-27 11:47 UTC, pan93412 approved these changes

2023-10-29 03:06 UTC, yuaanlin requested changes
The `static.TransformServerless` function is very simple, it copy the static files into `.zeabur/output/static` directory.

So when we handle static provider, it is just the same way as we handle static files of Node.js provider. The only different is `outputDir` is `./` (all source files).

2023-10-29 03:06 UTC, yuaanlin commented on pkg/zeaburpack/main.go
> +
```suggestion
	if t == types.PlanTypeStatic {
		println("Transforming build output to serverless format ...")
		m["outputDir"] = "."
		err = static.TransformServerless(*opt.ResultImage, *opt.Path, m)
		if err != nil {
			println("Failed to transform static serverless: " + err.Error())
			handleBuildFailed(err)
			return err
		}
	}
```

2023-10-29 03:06 UTC, yuaanlin commented on internal/static/TransformServerless.go
> +	err := utils.CopyFromImage(image, path.Join("/usr/share/nginx/html/static", meta["outputDir"])+"/.", path.Join(workdir, ".zeabur/output/static"))
```suggestion
	err := utils.CopyFromImage(image, path.Join("/src", meta["outputDir"])+"/.", path.Join(workdir, ".zeabur/output/static"))
```

2023-10-29 10:29 UTC, pan93412 commented
你又提交到binary了:(

2023-10-29 11:55 UTC, closed without merging