fix(plan/rust): Fix file missing due to rust build binary name
zeabur/zbpack pull request #210
Opened 2024-02-05 09:22 UTC by hackerchai

#### Description (required)

This issue fixes rust build missing binary file due to old serverless export method using fixed SubmoduleName.

#### Related issues & labels (optional)

- Closes ZEA-2557
- Suggested label: bug

2024-02-05 09:46 UTC, pan93412 requested changes

2024-02-05 09:46 UTC, pan93412 commented on internal/rust/template.Dockerfile
> +COPY --from=builder --chown=zeabur:zeabur /app/bin/server ./bin/server
```suggestion
COPY --from=builder --chown=zeabur:zeabur /app/bin/server /app/bin/server
```

Better to be explicit.

2024-02-05 09:46 UTC, pan93412 commented on internal/rust/template.Dockerfile
> +CMD ["./bin/server"]
```suggestion
CMD ["/app/bin/server"]
```

2024-02-06 03:33 UTC, pan93412 approved these changes

2024-02-06 03:36 UTC, yuaanlin approved these changes

2024-02-06 03:36 UTC, merged